import type { Country } from "./types";

export const COUNTRIES: Country[] = [
  // ── VFS Global ────────────────────────────────────────────
  {
    code: "fra",
    name: "Fransa",
    flag: "🇫🇷",
    popularCity: "Paris",
    destinationCode: "CDG",
    centers: ["İstanbul Şişli", "İstanbul Kadıköy", "Ankara", "İzmir"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/fra/",
    visible: false,
    tips: [
      "Rezervasyon tarihinden en az 3 ay önceden başvurun.",
      "Banka hesap özeti son 3 aya ait olmalı ve bakiye yeterli görünmelidir.",
      "Konaklama belgesi (otel veya davet mektubu) zorunludur.",
      "Seyahat sigortası en az 30.000€ teminat içermelidir.",
      "Randevu saatine 15 dakika önce merkezde olun.",
    ],
    requirements: ["Pasaport (6 ay geçerli)", "2 biyometrik fotoğraf", "Vize başvuru formu", "Seyahat sigortası (min. 30.000€)", "Uçuş rezervasyonu", "Otel rezervasyonu", "Banka ekstreleri (3 ay)", "Gelir belgesi"],
    processingTime: "10-15 iş günü",
    avgWait: "45-60 gün",
    bankRequirements: "Son 3 aylık banka hesap özeti (mümkünse apostilli). Kişi başı günlük min. 100€ karşılığı TL + konaklama + bilet tutarı görünür olmalı. Ani büyük nakit girişlerinden kaçının — hesap geçmişinde düzenlilik aranır.",
    rejectionReasons: [
      "Banka bakiyesi yetersiz veya dönemde ani artış var → 3+ ay önceden düzenli yatırım yapın",
      "Konaklama/uçuş rezervasyonu eksik ya da geçici değil → Onaylı rezervasyon belgesi sunun",
      "Türkiye'deki bağ belgesi (iş sözleşmesi, tapu, kira) yetersiz → İşveren yazısı + mülk belgesi ekleyin",
      "Seyahat amacı veya güzergahı inandırıcı değil → Gün gün seyahat planı hazırlayın",
      "Pasaport geçerlilik süresi seyahat sonrası 3 aydan az → Pasaportu yenileyin",
    ],
    coverGradient: ["#002395", "#ED2939"],
    cascadeFriendly: true,
  },
  {
    code: "che",
    name: "İsviçre",
    flag: "🇨🇭",
    popularCity: "Zürih",
    destinationCode: "ZRH",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/che/",
    visible: false,
    tips: [
      "İsviçre Schengen bölgesinde ancak AB üyesi değildir; başvuru süreçleri farklılık gösterebilir.",
      "Finansal kapasite için günlük 90 CHF yeterliliği kanıtlanmalıdır.",
      "İki kanton planlanıyorsa en uzun konaklamanın yapıldığı kanton belirleyicidir.",
      "Biyometrik veri verimi zorunludur, ilk kez başvuranlar merkeze gelmek zorundadır.",
    ],
    requirements: ["Pasaport", "Biyometrik fotoğraf", "Sigorta", "Finansal belgeler (90 CHF/gün)", "İstihdam belgesi", "Konaklama rezervasyonu"],
    processingTime: "15 iş günü",
    avgWait: "30-50 gün",
    bankRequirements: "Günlük 90 CHF (yaklaşık 100-110€) karşılığı finansal yeterlilik kanıtı zorunludur. Son 3 aylık banka özeti. İsviçre pahalı bir destinasyon; konaklama + ulaşım dahil toplam bütçe hesaplanmalı.",
    rejectionReasons: [
      "Günlük 90 CHF karşılığı yeterli bakiye kanıtlanamadı → Hesap özetinde rakamları netleştirin",
      "AB dışı statü nedeniyle ek belgeler eksik → VFS'in İsviçre özel belgeler listesini inceleyin",
      "Seyahat amacı belirsiz → Gün gün güzergah ve aktivite planı sunun",
      "Konaklama belgesi yetersiz veya geçici → Kesinleştirilmiş otel rezervasyonu sunun",
    ],
    coverGradient: ["#CC0000", "#FFFFFF"],
    cascadeFriendly: true,
  },
  {
    code: "nld",
    name: "Hollanda",
    flag: "🇳🇱",
    popularCity: "Amsterdam",
    destinationCode: "AMS",
    centers: ["İstanbul Şişli", "Ankara", "İzmir"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/nld/",
    visible: false,
    tips: [
      "Hollanda konsolosluğu 15 dakika geç kalınan başvuruları kabul etmez.",
      "Apostille onaylı belgelerin resmi tercümesi gerekmektedir.",
      "Parmak izi verisi 59 ay boyunca geçerlidir; bu sürede tekrar fiziksel başvuru gerekmez.",
      "Giriş amacı net olmalı: turizm, iş, aile ziyareti ayrı belgeler gerektirir.",
    ],
    requirements: ["Pasaport", "Fotoğraf", "Sigorta", "Banka ekstresi", "Konaklama", "Uçuş rezervasyonu"],
    processingTime: "10-15 iş günü",
    avgWait: "40-55 gün",
    bankRequirements: "Son 3 aylık eksiksiz banka özeti. Günlük yaklaşık 70-100€ karşılığı bakiye. Hollanda'nın belge incelemesi titizdir; hesap geçmişinde ani artış şüphe uyandırır. Mümkünse apostille veya banka imzalı resmi belge sunun.",
    rejectionReasons: [
      "Banka özeti düzensiz gelir veya ani artış gösteriyor → 3+ ay istikrarlı gelir akışı sağlayın",
      "Apostille veya resmi tasdik eksik → Belgeleri noter onaylı sunun",
      "Parmak izi için merkeze gelinmedi → Fiziksel randevu zorunludur",
      "Giriş amacı belgesi (turizm/iş/aile) yetersiz → Amaca özel belgeler hazırlayın",
    ],
    coverGradient: ["#AE1C28", "#21468B"],
    cascadeFriendly: true,
  },
  {
    code: "nor",
    name: "Norveç",
    flag: "🇳🇴",
    popularCity: "Oslo",
    destinationCode: "OSL",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/nor/",
    visible: false,
    tips: [
      "Norveç'te sezon farkı belirgindir; yaz randevuları Ocak'tan itibaren tükenmektedir.",
      "Kuzey Işıkları (Aurora) izlemek için Kasım–Mart, Lapland için ayrı belgeler istenir.",
      "İş amaçlı seyahatlerde davet mektubu Norveçli şirketten gelmelidir.",
    ],
    requirements: ["Pasaport", "Sigorta (min. 30.000€)", "Konaklama belgesi", "Finansal kanıt", "Seyahat planı"],
    processingTime: "10-15 iş günü",
    avgWait: "35-50 gün",
    bankRequirements: "Son 3 aylık banka özeti. Norveç NOK kullanır ve pahalıdır; günlük 100€+ karşılığı bakiye zorunludur. Kuzey Işıkları veya doğa turizmi için ekstra aktivite bütçesi gösterilmesi faydalıdır.",
    rejectionReasons: [
      "Norveç'te konaklama belgesi detaysız veya onaysız → Kesinleşmiş rezervasyon sunun",
      "Yaz sezonu için çok geç başvuru yapıldı → En az 3 ay önceden başvurun",
      "Seyahat güzergahı ve aktivite planı belirsiz → Gün bazlı plan hazırlayın",
      "Finansal yeterlilik Norveç maliyetleri için yetersiz → Bakiyeyi yükseltin",
    ],
    coverGradient: ["#EF2B2D", "#003680"],
    cascadeFriendly: false,
  },
  {
    code: "swe",
    name: "İsveç",
    flag: "🇸🇪",
    popularCity: "Stockholm",
    destinationCode: "ARN",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/swe/",
    visible: false,
    tips: [
      "Birden fazla Schengen ülkesi planlanıyorsa en uzun konaklamanın yapıldığı ülke konsolosluğuna başvurun.",
      "Başvuru sonuçları e-posta yerine VFS portalından takip edilir.",
      "Pasaport fotokopisi reddedilmez; orijinal pasaport mutlaka sunulmalıdır.",
    ],
    requirements: ["Pasaport (orijinal)", "Biyometrik fotoğraf", "Sigorta", "Banka ekstreleri", "İstihdam belgesi"],
    processingTime: "15 iş günü",
    avgWait: "30-45 gün",
    bankRequirements: "Son 3 aylık banka özeti. Standart Schengen finansal kriterleri geçerli. Çok ülkeli tur planlanıyorsa birleşik bütçe sunun; her ülkedeki konaklama masrafları ayrı gösterilebilir.",
    rejectionReasons: [
      "Başvuru yanlış ülke konsolosluğuna yapıldı → En uzun konaklama ülkesini seçin",
      "Orijinal pasaport yerine fotokopi sunuldu → Orijinal pasaport şarttır",
      "Finansal belgeler yetersiz → Tüm banka hesaplarını belgeleyin",
      "İsveç için biyometrik kaydı yok ve merkeze gelinmedi → Fiziksel başvuru zorunludur",
    ],
    coverGradient: ["#006AA7", "#FECC02"],
    cascadeFriendly: true,
  },
  {
    code: "mlt",
    name: "Malta",
    flag: "🇲🇹",
    popularCity: "Valletta",
    destinationCode: "MLA",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/mlt/",
    visible: true,
    tips: [
      "Malta vizesi diğer Schengen ülkelerine göre belge incelemesi daha hızlıdır.",
      "Yaz döneminde (Haziran–Ağustos) randevu bulmak zorlaşır, erkenden başvurun.",
      "Otel yerine Airbnb veya tatil villası kiralama belgeleri de kabul edilmektedir.",
    ],
    requirements: ["Pasaport", "2 fotoğraf", "Sigorta", "Konaklama belgesi", "Banka ekstresi", "Gelir belgesi"],
    processingTime: "7-10 iş günü",
    avgWait: "15-25 gün",
    bankRequirements: "Son 3 aylık banka özeti. Malta görece uygun maliyetli; günlük 50-70€ karşılığı yeterlidir. İlk Schengen için ideal bir ülke — finansal gereksinimler makul düzeyde.",
    rejectionReasons: [
      "Yaz sezonunda geç randevu alındı → Haziran öncesi başvurun",
      "Konaklama veya seyahat sigortası belgesi eksik → Tüm belgeleri eksiksiz sunun",
      "Banka özeti güncel değil (3 aydan eski) → Güncel özet alın",
    ],
    coverGradient: ["#CF142B", "#FFFFFF"],
  },
  {
    code: "isl",
    name: "İzlanda",
    flag: "🇮🇸",
    popularCity: "Reykjavik",
    destinationCode: "KEF",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/swe/",
    visible: true,
    tips: [
      "İzlanda vize başvuruları İsveç Konsolosluğu aracılığıyla alınmaktadır.",
      "Kuzey Işıkları sezonu Eylül–Mart; bu dönemde randevu talebi artar.",
      "Ring Road (Yüzük Yolu) turları için kiralık araç belgesi gerekmektedir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Seyahat planı", "Araç kiralama belgesi", "Finansal belgeler"],
    processingTime: "10 iş günü",
    avgWait: "10-20 gün",
    bankRequirements: "İsveç Konsolosluğu kriterleri geçerli. İzlanda pahalı bir destinasyon; günlük 120-150€ karşılığı bakiye önerilir. Ring Road turu için araç kiralama ücreti de bütçeye eklenmelidir.",
    rejectionReasons: [
      "İsveç Konsolosluğu yerine yanlış başvuru yeri seçildi → VFS İsveç üzerinden başvurun",
      "Ring Road veya araç kiralama planı sunulmadı → Kesinleştirilmiş araç rezervasyonu ekleyin",
      "İzlanda maliyetleri için finansal yeterlilik düşük → Bakiyeyi artırın",
    ],
    coverGradient: ["#003897", "#DC1E35"],
  },
  {
    code: "est",
    name: "Estonya",
    flag: "🇪🇪",
    popularCity: "Tallinn",
    destinationCode: "TLL",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/est/",
    visible: true,
    tips: [
      "Estonya dijital vize başvuru sistemiyle öne çıkan Schengen üyesidir.",
      "Tallinn'in tarihi şehir merkezi için konaklama belgesi kolayca düzenlenir.",
      "Balık avlama veya açıkhava aktivitesi için ek belgeler istenebilir.",
    ],
    requirements: ["Pasaport", "Fotoğraf", "Sigorta", "Konaklama", "Uçuş rezervasyonu"],
    processingTime: "5-10 iş günü",
    avgWait: "10-15 gün",
    bankRequirements: "Son 3 aylık banka özeti. Estonya ekonomik bir destinasyon; günlük 50-70€ karşılığı bakiye yeterlidir. İlk Schengen başvurusu için en kolay ülkelerden biri — red oranı düşük.",
    rejectionReasons: [
      "Temel belgeler (sigorta, konaklama) eksik → Eksiksiz paket hazırlayın",
      "Seyahat amacı belirsiz → Gün bazlı aktivite planı ekleyin",
      "Pasaport geçerliliği yetersiz → Seyahat sonrası 3 ay kalan pasaport gerekli",
    ],
    coverGradient: ["#0072CE", "#1B4F91"],
  },
  {
    code: "lva",
    name: "Letonya",
    flag: "🇱🇻",
    popularCity: "Riga",
    destinationCode: "RIX",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/lva/",
    visible: true,
    tips: [
      "Riga, Doğu Avrupa'nın en ekonomik Schengen destinasyonlarından biridir.",
      "Yüksek sezon (Haziran–Ağustos) dışında randevu bulmak oldukça kolaydır.",
    ],
    requirements: ["Pasaport", "Sigorta", "Finansal belgeler", "Konaklama", "İstihdam belgesi"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
    bankRequirements: "Son 3 aylık banka özeti. Riga uygun maliyetli; günlük 40-60€ karşılığı bakiye genellikle yeterlidir. İlk Schengen için ideal — Bask düşük, randevu kolay.",
    rejectionReasons: [
      "Konaklama belgesi eksik → Kesinleştirilmiş otel rezervasyonu sunun",
      "İstihdam belgesi veya gelir kanıtı eksik → İşveren yazısı ekleyin",
      "Finansal belgeler yetersiz → Tüm banka hesaplarını belgeleyin",
    ],
    coverGradient: ["#9E3039", "#FFFFFF"],
  },
  {
    code: "ltu",
    name: "Litvanya",
    flag: "🇱🇹",
    popularCity: "Vilnius",
    destinationCode: "VNO",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/ltu/",
    visible: true,
    tips: [
      "Banka hesap özetinin son 6 aylık dönemi istenebilir.",
      "Vilnius dışında Kaunas ve Klaipeda turlarını kapsayan seyahatlerde ulaşım planı eklenmelidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Banka ekstresi (6 ay)", "Konaklama belgesi"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
    bankRequirements: "Son 6 aylık banka özeti istenebilir (diğer ülkelerden uzun). Litvanya düşük maliyetli; günlük 40-60€ karşılığı yeterlidir. 6 aylık finansal geçmiş eksikse ret riski artar.",
    rejectionReasons: [
      "6 aylık banka özeti yetersiz veya sunulmadı → 6 aylık eksiksiz hesap özetini sunun",
      "Çok şehirli tur için ulaşım planı eksik → Şehirlerarası ulaşım belgesi ekleyin",
      "Konaklama belgesi eksik → Otel veya Airbnb rezervasyonu sunun",
    ],
    coverGradient: ["#FDB913", "#006A44"],
  },
  {
    code: "svn",
    name: "Slovenya",
    flag: "🇸🇮",
    popularCity: "Ljubljana",
    destinationCode: "LJU",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/svn/",
    visible: true,
    tips: [
      "Slovenya; Piran, Bled Gölü ve Triglav Milli Parkı gibi çeşitli destinasyonlara sahiptir, seyahat planı önemlidir.",
      "Belge eksikliğinde yeniden başvuru hakkı verilir; doğrudan ret olmaz.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama", "Seyahat planı", "Finansal belgeler"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
    bankRequirements: "Son 3 aylık banka özeti. Standart Schengen kriterleri. Seyahat planı detaylı sunulursa finansal değerlendirme daha olumlu sonuçlanır.",
    rejectionReasons: [
      "Seyahat planı eksik veya belirsiz → Bled, Ljubljana, Piran için ayrı konaklama belgesi ekleyin",
      "Konaklama belgesi yetersiz → Her destinasyon için ayrı rezervasyon sunun",
      "Finansal yeterlilik kanıtı yetersiz → Banka özetini ve gelir belgesini birlikte sunun",
    ],
    coverGradient: ["#003DA5", "#00A651"],
  },
  {
    code: "hrv",
    name: "Hırvatistan",
    flag: "🇭🇷",
    popularCity: "Dubrovnik",
    destinationCode: "DBV",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/hrv/",
    visible: true,
    tips: [
      "Hırvatistan Schengen'e Ocak 2023'te dahil oldu; eski vize bilgileri güncel olmayabilir.",
      "Yaz aylarında (Temmuz–Ağustos) Dalmaçya kıyısına talep yoğundur, çok önceden başvurun.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama belgesi", "Uçuş rezervasyonu", "Banka ekstresi"],
    processingTime: "10-15 iş günü",
    avgWait: "20-35 gün",
    bankRequirements: "Son 3 aylık banka özeti. Yaz sezonunda Dalmaçya kıyısı pahalı olabilir; bu dönem için günlük 100€+ karşılığı bakiye önerilir. Tekne/feribot turları planlanıyorsa bu masraflar da bütçede görünmeli.",
    rejectionReasons: [
      "2023 öncesi Hırvatistan vize deneyimi yanlış referans gösterildi → Schengen olarak başvurun",
      "Yaz sezonunda çok geç başvuru → En az 3-4 ay önceden başvurun",
      "Konaklama belgesi yetersiz → Her ada/şehir için ayrı rezervasyon ekleyin",
    ],
    coverGradient: ["#FF0000", "#0055A4"],
  },
  {
    code: "dnk",
    name: "Danimarka",
    flag: "🇩🇰",
    popularCity: "Kopenhag",
    destinationCode: "CPH",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/dnk/",
    visible: false,
    tips: [
      "VFS'de parmak izi alımı zorunludur, merkeze fiziksel görünüm şarttır.",
      "Kopenhag'da tur düzenleyen ajans faturası konaklama belgesi yerine geçebilir.",
    ],
    requirements: ["Pasaport", "Biyometrik fotoğraf", "Sigorta", "Finansal belgeler", "Konaklama"],
    processingTime: "10-15 iş günü",
    avgWait: "25-40 gün",
    bankRequirements: "Son 3 aylık banka özeti. Danimarka pahalı bir destinasyon; günlük 100-120€ karşılığı bakiye önerilir. Parmak izi için mutlaka merkeze fiziksel olarak gelinmeli.",
    rejectionReasons: [
      "Fiziksel başvuru yapılmadı, parmak izi kaydı eksik → Merkeze bizzat gidin",
      "Danimarka maliyetleri için finansal yeterlilik düşük → Bakiyeyi artırın",
      "Konaklama belgesi onaysız veya eksik → Oteller teyit belgesini sunun",
    ],
    coverGradient: ["#C60C30", "#FFFFFF"],
  },
  {
    code: "fin",
    name: "Finlandiya",
    flag: "🇫🇮",
    popularCity: "Helsinki",
    destinationCode: "HEL",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/fin/",
    visible: false,
    tips: [
      "Turistik amaçlı seyahatlerde kesin olmayan uçuş rezervasyonu da kabul edilmektedir.",
      "Lapland bölgesi (Kuzey Işıkları) için rehberlik veya kamp belgeleri eklenmelidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama", "Finansal belgeler"],
    processingTime: "10-15 iş günü",
    avgWait: "20-35 gün",
    bankRequirements: "Son 3 aylık banka özeti. Kuzey bölgeleri veya Lapland planlanıyorsa ek aktivite bütçesi ve rehberlik belgeleri gerekebilir. Günlük 80-100€ karşılığı önerilir.",
    rejectionReasons: [
      "Lapland aktivite planı (rehberlik, kamp) sunulmadı → Aktivite belgelerini ekleyin",
      "Finansal yeterlilik yetersiz → Tüm hesapları belgeleyin",
      "Sigorta Finlandiya'yı kapsamıyor → Schengen genelini kapsayan poliçe seçin",
    ],
    coverGradient: ["#003580", "#FFFFFF"],
  },
  {
    code: "aut",
    name: "Avusturya",
    flag: "🇦🇹",
    popularCity: "Viyana",
    destinationCode: "VIE",
    centers: ["İstanbul Şişli", "Ankara", "İzmir"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/aut/",
    visible: false,
    tips: [
      "Kayıt yaptırma (Anmeldung) belgesi bazı durumlarda istenebilir.",
      "Salzburg veya Innsbruck planlanıyorsa seyahat güzergahı netleştirilmelidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama belgesi", "Banka ekstresi", "Uçuş rezervasyonu"],
    processingTime: "10-15 iş günü",
    avgWait: "30-45 gün",
    bankRequirements: "Son 3 aylık banka özeti. Viyana konaklaması pahalı olabilir; günlük 80-100€ karşılığı bakiye önerilir. Kaskad vize için uygun bir ülke — 2. başvuruda çok girişli talep edilebilir.",
    rejectionReasons: [
      "Anmeldung (kayıt) belgesi sunulmadı → Konakladığınız adresin kaydını sunun",
      "Seyahat güzergahı belirsiz → Viyana dışı destinasyonlar için ayrı plan ekleyin",
      "Finansal yeterlilik yetersiz → Viyana maliyetleri için bakiyeyi artırın",
      "Pasaport geçerlilik süresi yetersiz → Seyahat sonrası 3 ay kalmalı",
    ],
    coverGradient: ["#ED2939", "#FFFFFF"],
    cascadeFriendly: true,
  },
  {
    code: "bel",
    name: "Belçika",
    flag: "🇧🇪",
    popularCity: "Brüksel",
    destinationCode: "BRU",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/bel/",
    visible: false,
    tips: [
      "Belçika, Schengen randevularının en kısıtlı olduğu ülkeler arasındadır.",
      "Brüksel'deki AB kurumlarını ziyaret amacıyla ayrı bir davet belgesi gerekebilir.",
    ],
    requirements: ["Pasaport", "Biyometrik fotoğraf", "Sigorta", "Finansal belgeler", "Konaklama"],
    processingTime: "15 iş günü",
    avgWait: "50-70 gün",
    bankRequirements: "Son 3 aylık banka özeti. Brüksel pahalıdır; günlük 100-120€ karşılığı bakiye önerilir. Randevu kıtlığı nedeniyle çok önceden başvurmak kritik önem taşır.",
    rejectionReasons: [
      "Randevu geç alındı, seyahat tarihine yetişmedi → 3-4 ay öncesinden harekete geçin",
      "AB kurumu ziyareti için davet belgesi eksik → Ziyaret edilecek kurum davetiyesini sunun",
      "Finansal yeterlilik yetersiz → Brüksel maliyetleri için bakiyeyi artırın",
      "Belgeler eksik → VFS Belçika kontrol listesini eksiksiz tamamlayın",
    ],
    coverGradient: ["#000000", "#F9CC12"],
  },
  {
    code: "bgr",
    name: "Bulgaristan",
    flag: "🇧🇬",
    popularCity: "Sofya",
    destinationCode: "SOF",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/bgr/",
    visible: true,
    tips: [
      "Bulgaristan hava ve deniz sınırlarında Schengen vizesi geçerlidir; kara sınırı ayrı uygulamaya tabidir.",
      "Karadeniz kıyısı (Burgaz, Nessebar) tatil planları için otel rezervasyonu yeterlidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama", "Finansal belgeler"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
    bankRequirements: "Son 3 aylık banka özeti. Bulgaristan ekonomik bir destinasyon; günlük 40-60€ karşılığı yeterlidir. Kara sınırı geçişi için farklı belgeler gerekebilir — hava yolu ile seyahat daha basit.",
    rejectionReasons: [
      "Kara sınırı geçişi için yanlış belge türü sunuldu → Hava/deniz yoluyla seyahat tercih edin",
      "Konaklama belgesi eksik → Kesinleştirilmiş otel rezervasyonu sunun",
      "Finansal yeterlilik çok düşük → Minimum gereksinimleri karşılayın",
    ],
    coverGradient: ["#00966E", "#D62612"],
  },
  {
    code: "lux",
    name: "Lüksemburg",
    flag: "🇱🇺",
    popularCity: "Lüksemburg Şehri",
    destinationCode: "LUX",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/lux/",
    visible: true,
    tips: [
      "Lüksemburg genellikle Belçika veya Hollanda ile birleşik tur planlanır.",
      "Küçük bir ülke olduğu için başvuru süreçleri görece hızlıdır.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama", "Finansal belgeler"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
    bankRequirements: "Son 3 aylık banka özeti. Çok ülkeli tur için birleşik bütçe belgesi sunulmalı. Lüksemburg pahalı olduğundan tüm tur için yeterli bütçe gösterilmeli.",
    rejectionReasons: [
      "Çok ülkeli tur bütçesi birleşik sunulmadı → Her ülke için ayrı masraf belgesi ekleyin",
      "Konaklama belgesi yetersiz → Kesinleştirilmiş otel rezervasyonu sunun",
      "Ana ziyaret ülkesi doğru seçilmedi → En uzun konaklama ülkesine başvurun",
    ],
    coverGradient: ["#EF3340", "#00A3E0"],
  },
  {
    code: "cze",
    name: "Çekya",
    flag: "🇨🇿",
    popularCity: "Prag",
    destinationCode: "PRG",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/cze/",
    visible: false,
    tips: [
      "Prag çok popüler olduğundan randevu kıtlığı yoğun dönemlerde yaşanabilir.",
      "Banka hesap özetinin apostilleli Türkçe-İngilizce versiyonu tercih edilir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Banka ekstresi", "Konaklama", "Uçuş rezervasyonu"],
    processingTime: "10-15 iş günü",
    avgWait: "25-40 gün",
    bankRequirements: "Son 3 aylık banka özeti (apostilleli önerilir). Prag popüler ve pahalı; günlük 80-100€ karşılığı bakiye önerilir. Apostille olmadan da kabul edilebilir ancak risk artar.",
    rejectionReasons: [
      "Yoğun dönemde geç randevu alındı → 2-3 ay öncesinden başvurun",
      "Banka özeti apostille/tasdik içermiyor → Mümkünse apostille ekleyin",
      "Seyahat planı yeterince detaylı değil → Prag dışı destinasyonlar için plan ekleyin",
    ],
    coverGradient: ["#D7141A", "#11457E"],
  },
  {
    code: "pol",
    name: "Polonya",
    flag: "🇵🇱",
    popularCity: "Varşova",
    destinationCode: "WAW",
    centers: ["İstanbul Şişli", "Ankara", "İzmir"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/pol/",
    visible: false,
    tips: [
      "Polonya, Türk başvuru sahiplerine yönelik görece hızlı işleyen bir süreç sunmaktadır.",
      "Zakopane veya Kraków planlanıyorsa ulaşım planı ayrıca eklenmelidir.",
    ],
    requirements: ["Pasaport", "Sigorta", "Konaklama", "Finansal belgeler", "İstihdam belgesi"],
    processingTime: "10-15 iş günü",
    avgWait: "20-30 gün",
    bankRequirements: "Son 3 aylık banka özeti. Polonya ekonomik bir destinasyon; günlük 50-70€ karşılığı bakiye yeterlidir. Düzenli gelir belgesi önemli.",
    rejectionReasons: [
      "İstihdam belgesi veya gelir kanıtı eksik → İşveren yazısı + maaş dökümü sunun",
      "Şehirlerarası ulaşım planı eksik → Kraków/Zakopane için ayrı ulaşım belgesi ekleyin",
      "Konaklama belgesi eksik → Her destinasyon için rezervasyon sunun",
    ],
    coverGradient: ["#DC143C", "#FFFFFF"],
  },
  {
    code: "prt",
    name: "Portekiz",
    flag: "🇵🇹",
    popularCity: "Lizbon",
    destinationCode: "LIS",
    centers: ["İstanbul Şişli", "Ankara"],
    centerOperator: "VFS Global",
    centerUrl: "https://visa.vfsglobal.com/tur/en/prt/",
    visible: false,
    tips: [
      "Portekiz, Türk başvuru sahiplerine karşı görece esnek bir değerlendirme politikası izlemektedir.",
      "Lizbon dışında Porto veya Algarve planlanıyorsa bölgesel konaklama belgeleri eklenmelidir.",
    ],
    requirements: ["Pasaport", "Fotoğraf", "Sigorta", "Konaklama", "Uçuş rezervasyonu", "Banka ekstresi", "Gelir belgesi"],
    processingTime: "10-15 iş günü",
    avgWait: "20-35 gün",
    bankRequirements: "Son 3 aylık banka özeti. Portekiz görece uygun maliyetli; günlük 60-80€ karşılığı bakiye genellikle yeterlidir. Schengen'in en esnek değerlendirme politikalarından biri.",
    rejectionReasons: [
      "Bölgesel konaklama belgesi eksik (Porto/Algarve planlanıyorsa) → Her bölge için ayrı rezervasyon sunun",
      "Finansal yeterlilik yetersiz → Bakiye ve gelir belgesini birlikte sunun",
      "Sigorta belgesi Portekiz'i kapsadığını açıkça belirtmiyor → Poliçe detayını gösterin",
    ],
    coverGradient: ["#006600", "#FF0000"],
    cascadeFriendly: true,
  },

  // ── iDATA ─────────────────────────────────────────────────
  {
    code: "deu",
    name: "Almanya",
    flag: "🇩🇪",
    popularCity: "Berlin",
    destinationCode: "BER",
    centers: ["İstanbul Şişli", "İstanbul Anadolu", "Ankara", "İzmir", "Bursa", "Antalya"],
    centerOperator: "iData",
    centerUrl: "https://idata.com.tr/",
    visible: false,
    tips: [
      "Almanya vizesi iDATA merkezleri üzerinden alınmaktadır; VFS Global ile karıştırmayın.",
      "Belge incelemesinde en titiz Schengen ülkelerinden biridir; eksik belge reddine yol açar.",
      "İş amaçlı seyahatte Alman iş ortağından davet mektubu şarttır.",
      "Finansal yeterlilik için günlük 45–50€ karşılığı TL yeterli görülmelidir.",
      "Banka hesabınızın en az 6 aylık geçmişini sunmanız tavsiye edilir.",
    ],
    requirements: ["Pasaport (seyahat sonrası 3 ay geçerli)", "2 biyometrik fotoğraf", "Başvuru formu", "Seyahat sigortası", "Uçuş & konaklama rezervasyonu", "Banka ekstresi (6 ay)", "Gelir belgesi / iş sözleşmesi", "Vergi levhası (serbest meslek)"],
    processingTime: "10-15 iş günü",
    avgWait: "40-70 gün",
    bankRequirements: "Son 6 aylık banka özeti zorunlu (diğer Schengen ülkelerinden daha uzun). Günlük 45-50€ karşılığı TL + konaklama + uçuş masrafı görünür olmalı. ANİ BÜYÜK NAKİT GİRİŞİ KESİNLİKLE YASAK — şüphe uyandırır ve redde yol açar. Aylık düzenli maaş/gelir görünür olmalı.",
    rejectionReasons: [
      "6 aylık banka özetinde ani büyük para girişi var → Organik düzenli geliri belgeleyin",
      "İş sözleşmesi veya gelir belgesi eksik → İşveren yazısı + son 3 aylık maaş bordrosu sunun",
      "Belge eksikliği var (en titiz Schengen) → iDATA kontrol listesini nokta nokta tamamlayın",
      "İş seyahatinde Alman şirketten davet mektubu yok → Davet mektubunu Almanya'dan alın",
      "Türkiye'deki bağ belgesi yetersiz → Tapu + iş sözleşmesi + vergi kaydı ekleyin",
    ],
    coverGradient: ["#000000", "#DD0000"],
    cascadeFriendly: true,
  },
  {
    code: "ita",
    name: "İtalya",
    flag: "🇮🇹",
    popularCity: "Roma",
    destinationCode: "FCO",
    centers: ["İstanbul Şişli", "İstanbul Anadolu", "Ankara", "İzmir", "Antalya", "Bursa"],
    centerOperator: "iData",
    centerUrl: "https://idata.com.tr/",
    visible: false,
    tips: [
      "İtalya vizesi iDATA merkezleri üzerinden alınmaktadır.",
      "İtalya 2026'da vize kotasını artırdı; fuar dönemleri (Ocak, Şubat, Kasım) dışında randevu bulmak kolaylaştı.",
      "Çok şehirli tur planlanıyorsa seyahat güzergahı belgesini detaylandırın.",
      "Biyometrik parmak izi ilk başvuruda merkezde alınır.",
      "Otel yerine Airbnb belgesi de konaklama kanıtı olarak kabul edilir.",
    ],
    requirements: ["Pasaport", "2 fotoğraf", "Sigorta (min. 30.000€)", "Konaklama belgesi", "Uçuş rezervasyonu", "Banka ekstresi", "Gelir belgesi"],
    processingTime: "10-15 iş günü",
    avgWait: "25-45 gün",
    bankRequirements: "Son 3 aylık banka özeti. Standart Schengen kriterleri (günlük 70-100€ karşılığı). Çok şehirli tur için tüm destinasyonlar için konaklama belgesi ve yeterli bütçe gösterilmeli.",
    rejectionReasons: [
      "Çok şehirli tur için güzergah belgesi eksik → Roma, Floransa, Venedik için ayrı plan sunun",
      "Parmak izi için merkeze gelinmedi → İlk başvuruda fiziksel katılım zorunlu",
      "Finansal yeterlilik yetersiz → Günlük harcama bütçesini belgeleyin",
      "Konaklama belgesi eksik veya geçici → Kesinleştirilmiş rezervasyon sunun",
    ],
    coverGradient: ["#009246", "#CE2B37"],
    cascadeFriendly: true,
  },

  // ── Kosmos Vize ───────────────────────────────────────────
  {
    code: "grc",
    name: "Yunanistan",
    flag: "🇬🇷",
    popularCity: "Atina",
    destinationCode: "ATH",
    centers: ["İstanbul", "Ankara", "İzmir", "Antalya", "Bursa"],
    centerOperator: "Kosmos",
    centerUrl: "https://www.kosmosvisa.com/",
    visible: true,
    tips: [
      "Yunanistan, Schengen ülkeleri arasında randevu bulmayı en kolaylaştıranlardan biridir.",
      "Kosmos Vize; İstanbul, Ankara, İzmir, Antalya ve Bursa'da hizmet verir.",
      "Yaz sezonunda (Haziran–Ağustos) Ege adaları talebi yüksektir; önceden başvurun.",
      "Ada tatili planı varsa her ada için ayrı konaklama belgesi hazırlayın.",
      "Çok girişli (multiple-entry) vize için önceki vize geçmişinizi belgeleyin.",
    ],
    requirements: ["Pasaport (3 ay geçerli)", "2 biyometrik fotoğraf", "Sigorta (min. 30.000€)", "Uçuş rezervasyonu", "Otel / kiralık villa belgesi", "Banka ekstresi (3 ay)", "Gelir belgesi"],
    processingTime: "3-7 iş günü",
    avgWait: "10-30 gün",
    bankRequirements: "Son 3 aylık banka özeti. Yunanistan görece esnek; günlük 50-80€ karşılığı bakiye genellikle yeterlidir. Ada tatili için villa/tekne kiralaması belgesi bütçeye eklenmelidir. İlk Schengen için mükemmel seçim.",
    rejectionReasons: [
      "Her ada için ayrı konaklama belgesi sunulmadı → Ada başına rezervasyon hazırlayın",
      "Çok girişli vize talebi için önceki Schengen geçmişi yetersiz → İlk başvuruda tekli vize alın",
      "Finansal yeterlilik düşük → Banka özeti + gelir belgesini birlikte sunun",
      "Sigorta Yunanistan adalarını kapsamıyor → Tüm Schengen geneli sigortası seçin",
    ],
    coverGradient: ["#0D5EAF", "#FFFFFF"],
  },

  // ── BLS International ─────────────────────────────────────
  {
    code: "esp",
    name: "İspanya",
    flag: "🇪🇸",
    popularCity: "Madrid",
    destinationCode: "MAD",
    centers: ["İstanbul", "Ankara"],
    centerOperator: "BLS International",
    centerUrl: "https://blsiber.com/tr/",
    visible: false,
    tips: [
      "BLS International, İspanya vize başvurularını Türkiye'de yönetmektedir.",
      "İspanya'ya ilk kez başvuranlarda biyometrik parmak izi zorunludur.",
      "Barcelona veya Endülüs gibi çok şehirli turlarda gün gün seyahat planı hazırlayın.",
      "Sigorta poliçesinin İspanya'yı da kapsadığına dair İngilizce onay belgesini ekleyin.",
      "Yaz sezonunda (Haziran–Eylül) randevu kıtlığı belirginleşir; 2-3 ay önceden harekete geçin.",
    ],
    requirements: ["Pasaport", "2 biyometrik fotoğraf", "Başvuru formu", "Sigorta (min. 30.000€)", "Uçuş & konaklama rezervasyonu", "Banka ekstresi", "Gelir belgesi"],
    processingTime: "10-15 iş günü",
    avgWait: "30-50 gün",
    bankRequirements: "Son 3 aylık banka özeti. BLS International titiz inceleme yapar. Günlük 100€ karşılığı bakiye önerilir. Sigorta poliçesinin İspanya'yı kapsadığına dair İngilizce onay belgesi zorunludur.",
    rejectionReasons: [
      "Biyometrik parmak izi için merkeze gelinmedi → Fiziksel başvuru zorunludur",
      "Yaz sezonunda çok geç başvuru yapıldı → En az 3 ay önceden harekete geçin",
      "Günlük güzergah planı eksik (çok şehirli tur) → Barselona, Sevilla, Granada için ayrı plan ekleyin",
      "Finansal yeterlilik yetersiz → Günlük 100€ karşılığı bakiye görünür olmalı",
      "Sigorta belgesi İngilizce onay içermiyor → İngilizce onaylı poliçe sunun",
    ],
    coverGradient: ["#AA151B", "#F1BF00"],
  },
  {
    code: "svk",
    name: "Slovakya",
    flag: "🇸🇰",
    popularCity: "Bratislava",
    destinationCode: "BTS",
    centers: ["İstanbul", "Ankara"],
    centerOperator: "BLS International",
    centerUrl: "https://blsiber.com/tr/",
    visible: true,
    tips: [
      "Slovakya vizesi BLS International merkezleri üzerinden alınmaktadır.",
      "Bratislava, Viyana'ya yakınlığı nedeniyle çift şehir turları için idealdir.",
      "Belge gereksinimleri diğer Schengen ülkeleriyle benzerdir; randevu bulma görece kolaydır.",
    ],
    requirements: ["Pasaport", "Fotoğraf", "Sigorta", "Konaklama belgesi", "Uçuş rezervasyonu", "Finansal belgeler"],
    processingTime: "7-10 iş günü",
    avgWait: "10-20 gün",
    bankRequirements: "Son 3 aylık banka özeti. Standart Schengen kriterleri. Slovakya uygun maliyetli; günlük 50-60€ karşılığı bakiye yeterlidir. İlk Schengen için kolay ve hızlı ülkelerden biri.",
    rejectionReasons: [
      "Konaklama belgesi eksik veya onaysız → Kesinleştirilmiş rezervasyon sunun",
      "Finansal yeterlilik yetersiz → Bakiye ve gelir belgesini birlikte sunun",
      "Seyahat planı belirsiz → Bratislava ve Viyana için ayrı güzergah belirtin",
    ],
    coverGradient: ["#FFFFFF", "#0B4EA2"],
  },

  // ── AS Visa Solutions ─────────────────────────────────────
  {
    code: "hun",
    name: "Macaristan",
    flag: "🇭🇺",
    popularCity: "Budapeşte",
    destinationCode: "BUD",
    centers: ["İstanbul", "Ankara"],
    centerOperator: "AS Visa Solutions",
    centerUrl: "https://www.asvisasolutions.com/",
    visible: true,
    tips: [
      "Macaristan vizesi AS Visa Solutions merkezleri aracılığıyla alınmaktadır.",
      "Budapeşte'nin tarihi bölgeleri için güzergah planı eklenmesi başvuruyu güçlendirir.",
      "Termal turizm (Szechenyi banyosu vb.) için aktivite planı eklenebilir.",
      "Randevu bulmak diğer büyük Schengen ülkelerine kıyasla görece kolaydır.",
    ],
    requirements: ["Pasaport", "Fotoğraf", "Sigorta", "Konaklama belgesi", "Uçuş rezervasyonu", "Banka ekstresi", "Gelir belgesi"],
    processingTime: "7-10 iş günü",
    avgWait: "10-25 gün",
    bankRequirements: "Son 3 aylık banka özeti. Macaristan uygun maliyetli; günlük 50-70€ karşılığı bakiye yeterlidir. AS Visa Solutions titiz belge incelemesi yapar — eksik belge ret nedenidir.",
    rejectionReasons: [
      "Konaklama veya güzergah planı eksik → Budapeşte için gün bazlı plan sunun",
      "Finansal yeterlilik yetersiz → Gelir belgesi + banka özetini birlikte sunun",
      "Türkiye'deki bağ belgesi sunulmadı → İşveren yazısı veya mülk belgesi ekleyin",
      "Seyahat amacı belirsiz → Aktivite ve turizm planını detaylandırın",
    ],
    coverGradient: ["#CE2939", "#436F4D"],
  },
];

export function formatTimeAgo(isoString: string): string {
  const diff = Date.now() - new Date(isoString).getTime();
  const minutes = Math.floor(diff / 60000);
  const hours = Math.floor(diff / 3600000);
  if (minutes < 60) return `${minutes} dakika önce`;
  if (hours < 24) return `${hours} saat önce`;
  return `${Math.floor(hours / 24)} gün önce`;
}
